# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Tang
subtitle: 'Tang Tang'
description: '个人博客'
keywords: blog,java
author: 汤晔飞
language: zh-CN
timezone: 'Asia/Shanghai'
email: 584856024@qq.com

# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
url: https://aner1001.github.io/blog3
root: /blog3/
permalink: :loc/:year/:month/:day/:hash/
permalink_defaults:
  loc: posts
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
marked:
  prependRoot: true
  postAsset: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

#播放aplayer js meting js全局插入控制。
aplayer:
   asset_inject: false
   meting: true

#豆瓣
douban:
  user: 229720114
  builtin: true
  book:
    title: 'This is my book title'
    quote: 'This is my book quote'
    meta: true
    comments: true
    top_img: https://cdn.jsdelivr.net/gh/aner1001/picBed/img/cover/top/m_book.jpg
    aside: true
  movie:
    title: 'This is my movie title'
    quote: 'This is my movie quote'
    meta: true
    comments: true
    top_img: https://cccccc.png
    aside: true
  game:
    title: 'This is my game title'
    quote: 'This is my game quote'
    meta: true
    comments: true
    top_img: https://cccccc.png
    aside: true
  timeout: 10000

#搜索
##本地
search:
  path: search.xml
  field: post
  content: true
##网络
algolia:
  applicationID: 'IPXEYFRVVA'
  apiKey: '9ece2c29d29a1caff00ab5e7a439e313'
  indexName: 'blog'

# 离线访问体验，基于Service Worker。offline config passed to sw-precache.
# offline:
#   maximumFileSizeToCacheInBytes: 10485760 # 緩存的最大文件大小，以字節為單位
#   staticFileGlobs:
#     - public/**/*.{js,html,css,png,jpg,gif,svg,webp,eot,ttf,woff,woff2}
#   # 靜態文件合集，如果你的站點使用了例如webp格式的文件，請將文件類型添加進去。
#   stripPrefix: public
#   verbose: true
#   runtimeCaching:
#     # CDNs - should be cacheFirst, since they should be used specific versions so should not change
#     - urlPattern: /* # 如果你需要加載CDN資源，請配置該選項，如果沒有，可以不配置。
#       handler: cacheFirst
#       options:
#         origin: cdn.jsdelivr.net # cdn资源的 url



# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: 'git'
  repo:
    github:
      url: https://github.com/aner1001/blog3.git
      branch: gh-pages
      token: $HEXO_GITHUB_TOKEN
